package nl.cwo_app.entity;
// Generated Feb 23, 2017 2:41:20 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.validation.constraints.NotNull;

/**
 * Cursist generated by hbm2java
 */
@Entity
public class Cursist implements java.io.Serializable {

  @GeneratedValue(strategy = GenerationType.AUTO)
  @Id
  private Long id;
  @NotNull
  private String voornaam;
  private String tussenvoegsel;
  private String achternaam;
  private String opmerkingen;
  @Temporal(javax.persistence.TemporalType.DATE)
  private Date paspoort;
  private String foto;
  
  @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "cursist")
  private Set<CursistBehaaldEisen> cursistBehaaldEisen = new HashSet(0);
  
  // TODO change this to lazy fetching, can't get this to work atm. problem is jackson serialization happens before object is loaded.
  @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL, mappedBy = "cursist")
  private Set<CursistHeeftDiploma> cursistHeeftDiplomas = new HashSet(0);


  public Cursist() {
  }

  public Cursist(String voornaam) {
    this.voornaam = voornaam;
  }
/*
  public Cursist(String voornaam, String tussenvoegsel, String achternaam, String opmerkingen, Date paspoort, String foto, Set cursistBehaaldEisens, Set cursistHeeftDiplomas) {
    this.voornaam = voornaam;
    this.tussenvoegsel = tussenvoegsel;
    this.achternaam = achternaam;
    this.opmerkingen = opmerkingen;
    this.paspoort = paspoort;
    this.foto = foto;
    this.cursistBehaaldEisen = cursistBehaaldEisens;
    this.cursistHeeftDiplomas = cursistHeeftDiplomas;
  }*/

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public String getVoornaam() {
    return this.voornaam;
  }

  public void setVoornaam(String voornaam) {
    this.voornaam = voornaam;
  }

  public String getTussenvoegsel() {
    return this.tussenvoegsel;
  }

  public void setTussenvoegsel(String tussenvoegsel) {
    this.tussenvoegsel = tussenvoegsel;
  }

  public String getAchternaam() {
    return this.achternaam;
  }

  public void setAchternaam(String achternaam) {
    this.achternaam = achternaam;
  }

  public String getOpmerkingen() {
    return this.opmerkingen;
  }

  public void setOpmerkingen(String opmerkingen) {
    this.opmerkingen = opmerkingen;
  }

  public Date getPaspoort() {
    return this.paspoort;
  }

  public void setPaspoort(Date paspoort) {
    this.paspoort = paspoort;
  }

  public String getFoto() {
    return this.foto;
  }

  public void setFoto(String foto) {
    this.foto = foto;
  }
  public Set getCursistBehaaldEisen() {
    return this.cursistBehaaldEisen;
  }

  public void setCursistBehaaldEisen(Set cursistBehaaldEisen) {
    this.cursistBehaaldEisen = cursistBehaaldEisen;
  }

  public Set getCursistHeeftDiplomas() {
    return this.cursistHeeftDiplomas;
  }

  public void setCursistHeeftDiplomas(Set cursistHeeftDiplomas) {
    this.cursistHeeftDiplomas = cursistHeeftDiplomas;
  }
}
