package nl.cwo_app.entity;
// Generated Feb 23, 2017 2:41:20 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

/**
 * Cursist generated by hbm2java
 */
@Entity
public class Cursist implements java.io.Serializable {

    @GeneratedValue(strategy = GenerationType.AUTO)
    @Id
    private Long id;
    @NotNull
    private String voornaam;
    private String tussenvoegsel;
    private String achternaam;
    private String opmerkingen;
    private boolean verborgen;
 
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date paspoort;

    @OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "cursist")
    private CursistFoto cursistFoto;

    @Transient
    private String fotoFileBase64;

    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "cursistId")
    private List<CursistBehaaldEis> cursistBehaaldEis = new ArrayList(0);

    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "cursistId")
    private List<CursistHeeftDiploma> cursistHeeftDiplomas = new ArrayList();

    public Cursist() {
    }

    public Cursist(String voornaam) {
        this.voornaam = voornaam;
    }

    public Long getId() {
        return this.id;
    }

    public String getFotoFileBase64() {
        return fotoFileBase64;
    }

    public void setFotoFileBase64(String fotoFileBase64) {
        this.fotoFileBase64 = fotoFileBase64;
    }

    public CursistFoto getCursistFoto() {
        return cursistFoto;
    }

    public void setCursistFoto(CursistFoto cursistFoto) {
        this.cursistFoto = cursistFoto;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getVoornaam() {
        return this.voornaam;
    }

    public void setVoornaam(String voornaam) {
        this.voornaam = voornaam;
    }

    public String getTussenvoegsel() {
        return this.tussenvoegsel;
    }

    public void setTussenvoegsel(String tussenvoegsel) {
        this.tussenvoegsel = tussenvoegsel;
    }

    public String getAchternaam() {
        return this.achternaam;
    }

    public void setAchternaam(String achternaam) {
        this.achternaam = achternaam;
    }

    public String getOpmerkingen() {
        return this.opmerkingen;
    }

    public void setOpmerkingen(String opmerkingen) {
        this.opmerkingen = opmerkingen;
    }

    public Date getPaspoort() {
        return this.paspoort;
    }

    public void setPaspoort(Date paspoort) {
        this.paspoort = paspoort;
    }

    public boolean isVerborgen() {
        return verborgen;
    }

    public void setVerborgen(boolean verborgen) {
        this.verborgen = verborgen;
    }
    
    public void setFoto(String foto) {
        if (cursistFoto == null) {
            cursistFoto = new CursistFoto();
        }
        cursistFoto.setCursist(this);
        cursistFoto.setImage(foto);
    }

    public List<CursistBehaaldEis> getCursistBehaaldEis() {
        return cursistBehaaldEis;
    }

    public void setCursistBehaaldEis(List<CursistBehaaldEis> cursistBehaaldEis) {
        this.cursistBehaaldEis = cursistBehaaldEis;
    }

    public List<CursistHeeftDiploma> getCursistHeeftDiplomas() {
        return cursistHeeftDiplomas;
    }

    public void setCursistHeeftDiplomas(List<CursistHeeftDiploma> cursistHeeftDiplomas) {
        this.cursistHeeftDiplomas = cursistHeeftDiplomas;
    }

    public List<CursistBehaaldEis> makeTheorieBehaaldEisList() {
        List<CursistBehaaldEis> cursistBehaaldTheorieEis = new ArrayList();
        for (CursistBehaaldEis cbe : cursistBehaaldEis) {
            if (cbe.checkTheorieEis()) {
                cursistBehaaldTheorieEis.add(cbe);
            }
        }
        return cursistBehaaldTheorieEis;
    }

}
