package nl.cwo_app.entity;
// Generated Feb 23, 2017 2:41:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;

/**
 * CursistHeeftDiploma generated by hbm2java
 */
@Entity
public class CursistHeeftDiploma implements java.io.Serializable {

  @GeneratedValue(strategy = GenerationType.AUTO)
  @Id
  private Long id;
  
  private Long cursistId;
  
  @ManyToOne(fetch = FetchType.EAGER)
  private Diploma diploma;

  @Temporal(javax.persistence.TemporalType.DATE)
  private Date diplomaBehaald = new Date();

  public CursistHeeftDiploma() {
  }

  public CursistHeeftDiploma(Long cursistId, Diploma cwoDiscipline) {
    this.cursistId = cursistId;
    this.diploma = cwoDiscipline;
  }

  public CursistHeeftDiploma(Long cursistId, Diploma diploma, Date diplomaBehaald) {
    this.cursistId = cursistId;
    this.diploma = diploma;
    this.diplomaBehaald = diplomaBehaald;
  }

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Long getCursist() {
    return this.cursistId;
  }

  public void setCursist(Long cursistId) {
    this.cursistId = cursistId;
  }

  public Diploma getDiploma() {
    return this.diploma;
  }

  public void setDiploma(Diploma diploma) {
    this.diploma = diploma;
  }

  public Date getDiplomaBehaald() {
    return this.diplomaBehaald;
  }

  public void setDiplomaBehaald(Date diplomaBehaald) {
    this.diplomaBehaald = diplomaBehaald;
  }
}
