package nl.cwo_app.entity;
// Generated Feb 23, 2017 2:41:20 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;

/**
 * CursistHeeftDiploma generated by hbm2java
 */
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class CursistHeeftDiploma implements java.io.Serializable {

  @GeneratedValue(strategy = GenerationType.AUTO)
  @Id
  private Long id;
  
  @ManyToOne(fetch = FetchType.LAZY)
  @JsonIgnore
  private Cursist cursist;
  
  @ManyToOne(fetch = FetchType.EAGER)
  private Diploma cwoDiscipline;
  
  @Temporal(javax.persistence.TemporalType.DATE)
  private Date theorieBehaald;
  
  @Temporal(javax.persistence.TemporalType.DATE)
  private Date praktijkBehaald;
  
  @Temporal(javax.persistence.TemporalType.DATE)
  private Date diplomaBehaald;

  public CursistHeeftDiploma() {
  }

  public CursistHeeftDiploma(Cursist cursist, Diploma cwoDiscipline) {
    this.cursist = cursist;
    this.cwoDiscipline = cwoDiscipline;
  }

  public CursistHeeftDiploma(Cursist cursist, Diploma cwoDiscipline, Date theorieBehaald, Date praktijkBehaald, Date diplomaBehaald) {
    this.cursist = cursist;
    this.cwoDiscipline = cwoDiscipline;
    this.theorieBehaald = theorieBehaald;
    this.praktijkBehaald = praktijkBehaald;
    this.diplomaBehaald = diplomaBehaald;
  }

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Cursist getCursist() {
    return this.cursist;
  }

  public void setCursist(Cursist cursist) {
    this.cursist = cursist;
  }

  public Diploma getCwoDiscipline() {
    return this.cwoDiscipline;
  }

  public void setCwoDiscipline(Diploma cwoDiscipline) {
    this.cwoDiscipline = cwoDiscipline;
  }

  public Date getTheorieBehaald() {
    return this.theorieBehaald;
  }

  public void setTheorieBehaald(Date theorieBehaald) {
    this.theorieBehaald = theorieBehaald;
  }

  public Date getPraktijkBehaald() {
    return this.praktijkBehaald;
  }

  public void setPraktijkBehaald(Date praktijkBehaald) {
    this.praktijkBehaald = praktijkBehaald;
  }

  public Date getDiplomaBehaald() {
    return this.diplomaBehaald;
  }

  public void setDiplomaBehaald(Date diplomaBehaald) {
    this.diplomaBehaald = diplomaBehaald;
  }
}
