package nl.cwo_app.entity;
// Generated Feb 23, 2017 2:41:20 PM by Hibernate Tools 4.3.1

import javax.persistence.*;
/**
 * CwoEisen generated by hbm2java
 */
@Entity
public class DiplomaEis implements java.io.Serializable {

  @GeneratedValue(strategy = GenerationType.AUTO)
  @Id
  private Long id;
  
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "diploma_id")
  private Diploma diploma;
  
  private String titel;
  
  private String omschrijving;
  
  private boolean theorie;
  
  
  public DiplomaEis() {
  }

  public DiplomaEis(Diploma cwoDiscipline, String titel) {
    this.diploma = cwoDiscipline;
    this.titel = titel;
  }

  public DiplomaEis(Diploma diploma, String titel, String omschrijving) {
    this.diploma = diploma;
    this.titel = titel;
    this.omschrijving = omschrijving;
  }

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Diploma getDiploma() {
    return this.diploma;
  }

  public void setDiploma(Diploma diploma) {
    this.diploma = diploma;
  }

  public String getTitel() {
    return this.titel;
  }

  public void setTitel(String titel) {
    this.titel = titel;
  }

  public String getOmschrijving() {
    return this.omschrijving;
  }

  public void setOmschrijving(String omschrijving) {
    this.omschrijving = omschrijving;
  }

    public boolean isTheorie() {
        return theorie;
    }

    public void setTheorie(boolean theorie) {
        this.theorie = theorie;
    }

}
